name: Mousetrap
version: 1.0
description: "Allows you to get to your site's Dasboard via the Escape key"
url: https://github.com/edalzell/statamic-mousetrap
developer: Erin Dalzell
developer_url: https://github.com/edalzell
